//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeOnboardingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificationData
    {
        public string CDID { get; set; }
        public string UPID { get; set; }
        public string CertificationID { get; set; }
        public string Category { get; set; }
        public string Title { get; set; }
        public string CertifiedBy { get; set; }
        public string IssuedDate { get; set; }
        public string ValidUpto { get; set; }
        public string IsEdited { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
