//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeOnboardingAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeeOnboardEntities : DbContext
    {
        public EmployeeOnboardEntities()
            : base("name=EmployeeOnboardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdditionalData> AdditionalDatas { get; set; }
        public virtual DbSet<CertificationData> CertificationDatas { get; set; }
        public virtual DbSet<EmployerData> EmployerDatas { get; set; }
        public virtual DbSet<FunctionalSkillData> FunctionalSkillDatas { get; set; }
        public virtual DbSet<InsuranceData> InsuranceDatas { get; set; }
        public virtual DbSet<MembershipData> MembershipDatas { get; set; }
        public virtual DbSet<PersonalData> PersonalDatas { get; set; }
        public virtual DbSet<QualificationData> QualificationDatas { get; set; }
        public virtual DbSet<TainingData> TainingDatas { get; set; }
        public virtual DbSet<TechnicalSkillData> TechnicalSkillDatas { get; set; }
        public virtual DbSet<UserOfferDetail> UserOfferDetails { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
