//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeOnboardingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployerData
    {
        public string EDID { get; set; }
        public string UPID { get; set; }
        public string EmployerName { get; set; }
        public string Designation { get; set; }
        public string Domain { get; set; }
        public string JoiningDate { get; set; }
        public string ReleivingDate { get; set; }
        public string IsEdited { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
