//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeOnboardingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileData
    {
        public string FID { get; set; }
        public string UPID { get; set; }
        public byte[] File { get; set; }
        public string FileName { get; set; }
        public string TypeOfFile { get; set; }
        public string FileType { get; set; }
        public string FileDescription { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
