//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeOnboardingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceData
    {
        public string IDID { get; set; }
        public string UPID { get; set; }
        public string RelationshipType { get; set; }
        public string FatherName { get; set; }
        public string FatherDOB { get; set; }
        public string MotherName { get; set; }
        public string MotherDOB { get; set; }
        public string FatherInLawName { get; set; }
        public string FatherInLawDOB { get; set; }
        public string MotherInLawName { get; set; }
        public string MotherInLawDOB { get; set; }
        public string MaritalStatus { get; set; }
        public string SpouseName { get; set; }
        public string SpouseDOB { get; set; }
        public string SpouseGender { get; set; }
        public string Child1Name { get; set; }
        public string Child1DOB { get; set; }
        public string Child1Gender { get; set; }
        public string Child2Name { get; set; }
        public string Child2DOB { get; set; }
        public string Child2Gender { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
