//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeOnboardingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class QualificationData
    {
        public string QDID { get; set; }
        public string UPID { get; set; }
        public string Qualification { get; set; }
        public string Institution { get; set; }
        public string University { get; set; }
        public string YearOfCompletion { get; set; }
        public string Percentage { get; set; }
        public string Grade { get; set; }
        public string IsEditable { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
