//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeOnboardingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechnicalSkillData
    {
        public string TSDID { get; set; }
        public string UPID { get; set; }
        public string Skill { get; set; }
        public string Version { get; set; }
        public string Type { get; set; }
        public string Expertise { get; set; }
        public string LastWorkedOn { get; set; }
        public string Experience { get; set; }
        public string IsEdited { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
