//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeOnboardingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOfferDetail
    {
        public int id { get; set; }
        public string name { get; set; }
        public string emailID { get; set; }
        public string createdDate { get; set; }
        public Nullable<bool> isSubmitted { get; set; }
    }
}
